#!/usr/bin/env python3
"""Generate frames_data.hpp from the frames/*/*.txt assets.

Mirrors the old Rust behavior (frames.rs): split each file on '\n' and drop the
last byte of every line -- every frame line ends in a '"' sentinel that guards
trailing padding from editors.
"""
import pathlib
import sys

EXPECT = {"1": 11, "2": 10, "3": 5}
DELIM = "KQFRAME"  # raw-string delimiter; must not appear in any frame line


def frame_text(path: pathlib.Path) -> str:
    lines = [ln[:-1] for ln in path.read_text(encoding="utf-8").split("\n") if ln]
    return "\n".join(lines)


def emit_set(name: str, key: str, root: pathlib.Path) -> str:
    files = sorted((root / "frames" / key).glob("*.txt"))
    assert len(files) == EXPECT[key], f"set {key}: {len(files)} != {EXPECT[key]}"
    frames = [frame_text(f) for f in files]
    for f in frames:
        assert f")%s\"" % DELIM not in f, "delimiter collision in frame data"
    items = ",\n".join(f'    R"{DELIM}({f}){DELIM}"' for f in frames)
    return f"inline constexpr std::string_view {name}[] = {{\n{items},\n}};"


def main() -> int:
    root = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[2])
    body = [
        "// Generated by tools/gen_frames.py -- do not edit.",
        "#pragma once",
        "#include <string_view>",
        "",
        emit_set("SET1", "1", root),
        "",
        emit_set("SET2", "2", root),
        "",
        emit_set("SET3", "3", root),
        "",
        "inline constexpr std::string_view STATIC_FRAME = SET1[0];",
    ]
    out.write_text("\n".join(body) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
